name: this
networks:
    this-network:
        driver: bridge

services:
    php:
        container_name: ${PROJECT_SLUG}_php
        build:
            context: ./php
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        networks: [this-network]
        volumes:
            - ../:/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            KAFKA_BROKER: kafka:9092

    nginx:
        container_name: ${PROJECT_SLUG}_nginx
        image: ${NGINX_DOCKER_IMAGE}
        networks: [this-network]
        depends_on:
            - php
        ports:
            - "${NGINX_PORT:-8050}:80"
        volumes:
            - ../:/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
