name: this
networks:
    this-network:
        driver: bridge

volumes:
    this_mysql_data:

services:
    php:
        container_name: ${PROJECT_SLUG}_php
        build:
            context: ./php
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        networks: [this-network]
        volumes:
            - ../:/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            KAFKA_BROKER: kafka:9092

    nginx:
        container_name: ${PROJECT_SLUG}_nginx
        image: ${NGINX_DOCKER_IMAGE}
        networks: [this-network]
        depends_on:
            - php
        ports:
            - "${NGINX_PORT:-8050}:80"
        volumes:
            - ../:/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    mysql:
        container_name: ${PROJECT_SLUG}_db
        image: ${MYSQL_DOCKER_IMAGE:-mysql:8.0.43}
        networks: [this-network]
        ports:
            - "${MYSQL_PORT:-3380}:3306"
        volumes:
            - this_mysql_data:/var/lib/mysql
        env_file:
            - ./.env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
            MYSQL_USER: ${MYSQL_USER:-app}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}